[phases.setup]
nixPkgs = [
  "python39",
  "python39Packages.pip",
  "chromium",
  "xvfb-run",
  "fontconfig",
  "dejavu_fonts"
]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Build phase complete'",
  "echo 'Chromium path:' $(which chromium || echo 'not found')",
  "echo 'Display setup: DISPLAY=$DISPLAY'"
]

[start]
cmd = "xvfb-run -a -s '-screen 0 1920x1080x24' python -m uvicorn backend.api:app --host 0.0.0.0 --port $PORT"

[variables]
DISPLAY = ":99" 