[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
# Railway will automatically set RAILWAY_ENVIRONMENT=production
PORT = "8000" 